name: Pipeline

on:
 push:

jobs:

 build:

   runs-on: ubuntu-latest

   steps:

     - name: Clonacion de codigo
       uses: actions/checkout@v4

     - name: Setup Java JDK
       uses: actions/setup-java@v4.2.1
       with:
        java-version: '8'
        distribution: 'temurin'

     - name: Compilacion
       run: |
        mvn package

     - name: Ejecucion Test Unitarios
       run: |
        mvn package test

     - name: Setup Java JDK
       uses: actions/setup-java@v4.2.1
       with:
        java-version: '17'
        distribution: 'temurin'     

     - name: Analisis SonarCloud
        run:|
         mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
         -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
         -Dsonar.host.url=https://sonarcloud.io \
         -Dsonar.organization=maspee \
         -Dsonar.projectKey=maspee_microservicio-java
